@startuml

interface ILibRteProcessHandler
interface ILibRteModuleConfig

LibRteDriver -- ILibRteModuleConfig 
LibRteDriver -- ILibRteProcessHandler

EtherCatImplementation *-- LibRteProcessHandlerP0EtherCat
EtherCatImplementation *-- LibRteProcessHandlerP1EtherCat
EtherCatImplementation *-- LibRteProcessHandlerP2EtherCat
EtherCatImplementation *-- LibRteModuleConfigEtherCat
EtherCat --* EtherCatImplementation 
LibRteDriver --o EtherCatImplementation 
Cia402 --o EtherCatImplementation 


LibRteProcessHandlerP0EtherCat ..|> ILibRteProcessHandler
LibRteProcessHandlerP1EtherCat ..|> ILibRteProcessHandler
LibRteProcessHandlerP2EtherCat ..|> ILibRteProcessHandler
LibRteModuleConfigEtherCat ..|> ILibRteModuleConfig

class Cia402
note top: <b>Feldbus Profil.</b>\nWird von außen vorgegeben.\nAktuell noch konkret!

class LibRteDriver
note top: Wird durch den GeneralComManager\nbei der Initialisierung übergeben.

class EtherCat
note top: Plattform Implementierung EtherCat

interface ILibRteProcessHandler
note bottom: Interface des LibRteDriver für azyklische arbeiten.

interface ILibRteModuleConfig
note bottom: Abfrage der LibRte Modul Konfiguration
@enduml